site_name: NMDC Documentation
site_url: https://microbiomedata.org/
site_description: NMDC Documentation.
site_author: The NMDC Team

repo_url: https://github.com/microbiomedata/NMDC_documentation
edit_uri: ""

theme:
    name: readthedocs
    features:
        - navigation.instant

nav:
    - Overview: overview/0_overview.md
    - Home: standards/home.md
    - NMDC Schema: standards/index.md
    - NMDC Metadata Standards Documentation:  standards/Metadata_Documentation_Overview.md 
    - NMDC Schema Validation: standards/schema-validation.md
    - Identifiers in NMDC: standards/identifiers.md
    - MIxS Soil Package: standards/NMDC_MIxS_Soil_documentation.md
    - Credits: standards/credits.md   
    
markdown_extensions:
    - admonition
    - attr_list
    - def_list
    
extra_css:
    - css/extra.css

plugins:
    - search
    #- awesome-pages
    - redirects:
        redirect_maps:
            index.md: overview/0_overview.md